version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-dev
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ENV_ORACLE_PASSWORD}
      ORACLE_DATABASE: ${ENV_ORACLE_DATABASE}
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
